### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by HJain13** [HJain13/Primitive-Database#2]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)

License is MIT

- [ ] Add Usage Examples

- [ ] Add Screenshots

- [ ] Add License

**Comment by jangidkrishna** [comment]
created a pull request have a look and  please label it hacktober fest 
#4

**Comment by jangidkrishna** [comment]
#4

**Comment by apfohl** [comment]
Please have a look at PR #6.
